### ISSUE TITLE
Improvement/Add Support for Pseudo parameters

### ISSUE THREAD

**Issue by theonlymastermind** [cooperwalbrun/aws-iam-actions-support#9]
Firstly, great WebApp!

Submitting a Feature Request to cater for Pseudo parameters as well as the variations of resource types:

Type: "AWS::IAM::Policy"
Type: "AWS::IAM::ManagedPolicy"

The key Pseudo Params for my common use cases would b:

```
${AWS::AccountId}
${AWS::Region}
${AWS::Partition}
```

Where AWS::StackName would also be useful for conditions such as 
```
            Condition:
              StringLike:
                aws:ResourceTag/aws:cloudformation:stack-name:
                  - !Ref AWS::StackName
```

Cheers

**Comment by cooperwalbrun** [comment]
Thanks for the feedback. I have to meditate on ways to implement this a bit, because (1) it introduces a new kind of input (a variable reference) to the policy generator and (2) it only applies to the CloudFormation syntax. If you have any ideas for how you could see this manifesting in the interface (ergonomically speaking), let me know.
